### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'sparse'

### ISSUE THREAD

**Issue by team2-research-easy** [tencent-quantum-lab/tensorcircuit#198]
## Issue Description

importing the tensorcircuit gives following error:'module 'tensorflow' has no attribute 'sparse'

## How to Reproduce

```python
# Include a minimal snippet of the code that produces the error here.

import tensorcircuit as tc

```

### Error Output

```python
# Include the unexpected output or error log here
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-5db2005a1af1> in <module>
----> 1 import tensorcircuit as tc

c:\users\sys-73\appdata\local\programs\python\python37\lib\site-packages\tensorcircuit\__init__.py in <module>
     24 )  # prerun of set hooks
     25 from . import gates
---> 26 from . import basecircuit
     27 from .gates import Gate
     28 from .circuit import Circuit, expectation

c:\users\sys-73\appdata\local\programs\python\python37\lib\site-packages\tensorcircuit\basecircuit.py in <module>
     12 
     13 from . import gates
---> 14 from .quantum import (
     15     QuOperator,
     16     QuVector,

c:\users\sys-73\appdata\local\programs\python\python37\lib\site-packages\tensorcircuit\quantum.py in <module>
   1168         compiled_jit = _id
   1169     else:
-> 1170         compiled_jit = partial(get_backend("tensorflow").jit, jit_compile=True)
   1171 
   1172     def heisenberg_hamiltonian(

c:\users\sys-73\appdata\local\programs\python\python37\lib\site-packages\tensorcircuit\backends\backend_factory.py in get_backend(backend)
     55     if backend in _INSTANTIATED_BACKENDS:
     56         return _INSTANTIATED_BACKENDS[backend]
---> 57     _INSTANTIATED_BACKENDS[backend] = _BACKENDS[backend]()
     58 
     59     return _INSTANTIATED_BACKENDS[backend]

c:\users\sys-73\appdata\local\programs\python\python37\lib\site-packages\tensorcircuit\backends\tensorflow_backend.py in __init__(self)
    377             )
    378         tf = tensorflow
--> 379         tf.sparse.SparseTensor.__add__ = tf.sparse.add
    380         self.minor = int(tf.__version__.split(".")[1])
    381         self.name = "tensorflow"

AttributeError: module 'tensorflow' has no attribute 'sparse'
```

## Environment Context

os: windows 11
python: 3.7
tensorflow==2.11.0
tensorcircuit==0.11.0

**Comment by refraction-ray** [comment]
please try reinstalling all packages in a new env (and better use newer python such as python3.10)

**Comment by team2-research-easy** [comment]
@refraction-ray  thanks. it works in python 3.10
